version: '3.5'

networks:
  services-network:
    driver: bridge

services:
  mongo-dev:
    image: mongo:latest
    container_name: mongo-dev
    hostname: mongo-dev
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=qwe123
    restart: always
    healthcheck:
      test:
        [
          "CMD",
          "mongo",
          "--quiet",
          "127.0.0.1/test",
          "--eval",
          "'quit(db.runCommand({ ping: 1 }).ok ? 0 : 2)'",
        ]
      interval: 10s
      timeout: 10s
      retries: 5
    networks:
      - services-network

  mysql-dev:
    image: mysql:8.0
    restart: always
    container_name: mysql-dev
    hostname: mysql-dev
    environment:
      - MYSQL_DATABASE=root
      - MYSQL_ROOT_PASSWORD=qwe123
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    networks:
      - services-network

  totem-food-order-service:
    container_name: totem-food-order-service
    hostname: totem-food-order-service
    image: jeffersoncleyson/totem-food-order-service:latest
    environment:
      - INSPECT_BEANS=false
      - SPRING_PROFILES_ACTIVE=dev
      ## Database
      - ORDER_MONGODB_URI=mongodb://root:qwe123@mongo-dev:27017/totem-food-order?authSource=admin
      ## Email
      - SMTP_HOST=mailhog
      - SMTP_PORT=1025
      - SMTP_USERNAME=username
      - SMTP_PASSWORD=password
      - SMTP_AUTH_ENABLED=false
      - SMTP_TLS_ENABLED=false
      - SMTP_EMAIL=contato@totem.food.service.com.br
      ## Internal Communication
      - MS_INTERNAL_CUSTOMER=http://totem-food-customer-service:8081
      - MS_INTERNAL_PAYMENT=http://totem-food-payment-service:8082
    ports:
      - "8080:8080"
    # depends_on:
    #   mongo-dev:
    #     condition: service_healthy
    networks:
      - services-network

  totem-food-payment-service:
    container_name: totem-food-payment-service
    hostname: totem-food-payment-service
    image: jeffersoncleyson/totem-food-payment-service:latest
    environment:
      - INSPECT_BEANS=false
      - SPRING_PROFILES_ACTIVE=dev
      ## Database
      - PAYMENT_DB_URL=jdbc:mysql://mysql-dev:3306/db_payment?createDatabaseIfNotExist=true
      - PAYMENT_DB_USERNAME=root
      - PAYMENT_DB_PASSWORD=qwe123
      ## Payment Gateway
      - PAYMENT_GATEWAY_URL=https://api.mercadopago.com
      - PAYMENT_CALLBACK_URL=https://composed-firefly-willingly.ngrok-free.app/v1/totem/payment/callback
      - STORE_ID=${STORE_ID}
      - STORE_TOKEN=${STORE_TOKEN}
      - STORE_USER_ID=${STORE_USER_ID}
      ## Internal Communication
      - MS_INTERNAL_ORDER=http://totem-food-order-service:8080
      - MS_INTERNAL_CUSTOMER=http://totem-food-customer-service:8081
    ports:
      - "8082:8082"
    depends_on:
      mysql-dev:
        condition: service_healthy
    networks:
      - services-network

  totem-food-customer-service:
    container_name: totem-food-customer-service
    hostname: totem-food-customer-service
    image: jeffersoncleyson/totem-food-customer-service:latest
    environment:
      - INSPECT_BEANS=false
      - SPRING_PROFILES_ACTIVE=dev
    ports:
      - "8081:8081"
    networks:
      - services-network

  mailhog:
    container_name: mailhog
    hostname: mailhog
    image: mailhog/mailhog:latest
    restart: always
    ports:
      - 1025:1025
      - 8025:8025
    networks:
      - services-network