version: '3.5'

networks:
  services-network:
    driver: bridge

volumes:
  mongo_data:

services:
  mongo-dev:
    image: mongo:latest
    container_name: mongo-dev
    hostname: mongo-dev
    env_file: envs/mongo/.env
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo mongo-dev:27017/test --quiet
      interval: 30s
      timeout: 2s
      retries: 5
      start_period: 5s
    networks:
      - services-network

  mysql-dev:
    image: mysql:8.0
    restart: always
    container_name: mysql-dev
    hostname: mysql-dev
    env_file: envs/mysql/.env
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    networks:
      - services-network

  totem-food-order-service:
    container_name: totem-food-order-service
    hostname: totem-food-order-service
    image: jeffersoncleyson/totem-food-order-service:latest
    env_file: envs/order/.env
    ports:
      - "8080:8080"
      - "8780:8787" # DEBUG
    depends_on:
      mongo-dev:
        condition: service_healthy
    networks:
      - services-network

  totem-food-payment-service:
    container_name: totem-food-payment-service
    hostname: totem-food-payment-service
    image: jeffersoncleyson/totem-food-payment-service:latest
    env_file: envs/payment/.env
    ports:
      - "8082:8082"
      - "8782:8787" # DEBUG
    depends_on:
      mysql-dev:
        condition: service_healthy
    networks:
      - services-network

  totem-food-customer-service:
    container_name: totem-food-customer-service
    hostname: totem-food-customer-service
    image: jeffersoncleyson/totem-food-customer-service:latest
    env_file: envs/customer/.env
    ports:
      - "8081:8081"
      - "8781:8787" # DEBUG
    networks:
      - services-network

  mailhog:
    container_name: mailhog
    hostname: mailhog
    image: mailhog/mailhog:latest
    restart: always
    ports:
      - 1025:1025
      - 8025:8025
    networks:
      - services-network