version: '3.5'

networks:
  services-network:
    driver: bridge

volumes:
  mongo_data:

services:
  mongo-dev:
    image: mongo:latest
    container_name: mongo-dev
    hostname: mongo-dev
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=qwe123
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo mongo-dev:27017/test --quiet
      interval: 30s
      timeout: 2s
      retries: 5
      start_period: 5s
    networks:
      - services-network

  mysql-dev:
    image: mysql:8.0
    restart: always
    container_name: mysql-dev
    hostname: mysql-dev
    environment:
      - MYSQL_DATABASE=root
      - MYSQL_ROOT_PASSWORD=qwe123
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    networks:
      - services-network

  totem-food-order-service:
    container_name: totem-food-order-service
    hostname: totem-food-order-service
    image: jeffersoncleyson/totem-food-order-service:latest
    environment:
      - INSPECT_BEANS=false
      ## Database
      - ORDER_MONGODB_URI=mongodb://root:qwe123@mongo-dev:27017/totem-food-order?authSource=admin
      ## Email
      - SMTP_HOST=mailhog
      - SMTP_PORT=1025
      - SMTP_USERNAME=username
      - SMTP_PASSWORD=password
      - SMTP_AUTH_ENABLED=false
      - SMTP_TLS_ENABLED=false
      - SMTP_EMAIL=contato@totem.food.service.com.br
      ## Internal Communication
      - MS_INTERNAL_CUSTOMER=http://totem-food-customer-service:8081
      - MS_INTERNAL_PAYMENT=http://totem-food-payment-service:8082
    ports:
      - "8080:8080"
      - "8780:8787" # DEBUG
    depends_on:
      mongo-dev:
        condition: service_healthy
    networks:
      - services-network

  totem-food-payment-service:
    container_name: totem-food-payment-service
    hostname: totem-food-payment-service
    image: jeffersoncleyson/totem-food-payment-service:latest
    environment:
      - INSPECT_BEANS=false
      - SPRING_PROFILES_ACTIVE=dev
      ## Database
      - PAYMENT_DB_URL=jdbc:mysql://mysql-dev:3306/db_payment?createDatabaseIfNotExist=true
      - PAYMENT_DB_USERNAME=root
      - PAYMENT_DB_PASSWORD=qwe123
      ## Payment Gateway
      - PAYMENT_GATEWAY_URL=https://api.mercadopago.com
      - PAYMENT_CALLBACK_URL=https://composed-firefly-willingly.ngrok-free.app/v1/totem/payment/callback
      - STORE_ID=${STORE_ID}
      - STORE_TOKEN=${STORE_TOKEN}
      - STORE_USER_ID=${STORE_USER_ID}
      ## Internal Communication
      - MS_INTERNAL_ORDER=http://totem-food-order-service:8080
      - MS_INTERNAL_CUSTOMER=http://totem-food-customer-service:8081
    ports:
      - "8082:8082"
      - "8782:8787" # DEBUG
    depends_on:
      mysql-dev:
        condition: service_healthy
    networks:
      - services-network

  totem-food-customer-service:
    container_name: totem-food-customer-service
    hostname: totem-food-customer-service
    image: jeffersoncleyson/totem-food-customer-service:latest
    environment:
      - INSPECT_BEANS=false
      - SPRING_PROFILES_ACTIVE=dev
    ports:
      - "8081:8081"
      - "8781:8787" # DEBUG
    networks:
      - services-network

  mailhog:
    container_name: mailhog
    hostname: mailhog
    image: mailhog/mailhog:latest
    restart: always
    ports:
      - 1025:1025
      - 8025:8025
    networks:
      - services-network