name: Test
on:
  push:
    branches:
      - main
      - develop
    tags:
      - v*
  pull_request:
    types: [opened, synchronize, reopened]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v1
    - name: Run docker-compose stack
      run: docker-compose -f docker-compose.yaml up -d

    - name: Check docker-compose stack
      run: docker-compose -f docker-compose.yaml ps

    - name: Set Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: 16.x

    - name: Run install
      uses: borales/actions-yarn@v4
      with:
        cmd: install

    - name: Make envfile
      uses: SpicyPizza/create-envfile@v2.0
      with:
        TIMEOUT: 5000
        USER_IDENTIFIER: 12345678901
        TOTEM_PATH_NAME: totem
        ADMINISTRATIVE_PATH_NAME: administrative
        CUSTOMER_VERSION: v1
        ORDER_VERSION: v1
        PAYMENT_VERSION: v1
        PROFILE: LOCAL
        CUSTOMER_SERVICE_ADDR: http://localhost:8081
        ORDER_SERVICE_ADDR: http://localhost:8080
        PAYMENT_SERVICE_ADDR: http://localhost:8082
        STORE_ID: ${{ secrets.STORE_ID }}
        STORE_TOKEN: ${{ secrets.STORE_TOKEN }}
        STORE_USER_ID: ${{ secrets.STORE_USER_ID }}


    - name: Run install
      uses: borales/actions-yarn@v4
      with:
        cmd: test

    - name: Stop docker-compose stack
      run: docker-compose -f docker-compose.yaml down -v

    - name: Check after stop docker-compose stack
      run: docker-compose -f docker-compose.yaml ps