name: Test
on:
  push:
    branches:
      - main
      - develop
    tags:
      - v*
  pull_request:
    types: [opened, synchronize, reopened]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v1
    - name: Run docker-compose stack
      run: docker-compose -f docker-compose.yaml up -d

    - name: Check docker-compose stack
      run: docker-compose -f docker-compose.yaml ps

    - name: Set Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: 16.x

    - name: Run install
      uses: borales/actions-yarn@v4
      with:
        cmd: install

    - name: Provide .env
      run: echo ${{ secrets.ENV_FILE }} >> .env

    - name: Run install
      uses: borales/actions-yarn@v4
      with:
        cmd: test

    - name: Stop docker-compose stack
      run: docker-compose -f docker-compose.yaml down -v

    - name: Check after stop docker-compose stack
      run: docker-compose -f docker-compose.yaml ps